version: '3.5'

volumes:
  sock01:
  sock02:

services:
  api01:
    image: marcoscarvalho04/rinha-backend-marcos-2026:latest
    hostname: api01
    volumes:
      - sock01:/run
    environment:
      - SOCKET_PATH=/run/api.sock
      - GOGC=off
      - GOMEMLIMIT=210MiB
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "250MB"

  api02:
    image: marcoscarvalho04/rinha-backend-marcos-2026:latest
    hostname: api02
    volumes:
      - sock02:/run
    environment:
      - SOCKET_PATH=/run/api.sock
      - GOGC=off
      - GOMEMLIMIT=210MiB
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "250MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sock01:/run/api01
      - sock02:/run/api02
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
