version: '3.5'

volumes:
  sock01:
  sock02:

services:
  api01:
    build: .
    image: rinha-api:latest
    hostname: api01
    volumes:
      - sock01:/run
    environment:
      - SOCKET_PATH=/run/api.sock
      - GOGC=off
      - GOMEMLIMIT=115MiB
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "140MB"

  api02:
    image: rinha-api:latest
    hostname: api02
    volumes:
      - sock02:/run
    environment:
      - SOCKET_PATH=/run/api.sock
      - GOGC=off
      - GOMEMLIMIT=115MiB
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "140MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sock01:/run/api01
      - sock02:/run/api02
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"
